[project]
name = "niffler-py-st3"
version = "0.1.0"
description = ""
authors = [
    {name = "Zalina Kodz",email = "kod3ik87@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "pbreflect (>=1.1.0,<2.0.0)",
    "allure-pytest (>=2.15.0,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--alluredir=../allure-results"
